### ISSUE TITLE
Sink does not work with Microsoft.Azure.DocumentDB 1.15.0

### ISSUE THREAD

**Issue by acgritt** [serilog/serilog-sinks-azuredocumentdb#60]
There has apparently been a change within Microsoft.Azure.DocumentDB 1.15.0 that doesn't work with the sink.  The following error is generated when using it with the latest version of the Azure DocumentDB Sink.

System.MissingMethodException: Method not found: 'Void Microsoft.Azure.Documents.Client.DocumentClient..ctor(System.Uri, System.String, Microsoft.Azure.Documents.Client.ConnectionPolicy, System.Nullable`1)'.
   at Serilog.Sinks.AzureDocumentDb.AzureDocumentDBSink..ctor(Uri endpointUri, String authorizationKey, String databaseName, String collectionName, IFormatProvider formatProvider, Boolean storeTimestampInUtc, Protocol connectionProtocol, Nullable`1 timeToLive)
   at Serilog.LoggerConfigurationAzureDocumentDBExtensions.AzureDocumentDB(LoggerSinkConfiguration loggerConfiguration, Uri endpointUri, String authorizationKey, String databaseName, String collectionName, LogEventLevel restrictedToMinimumLevel, IFormatProvider formatProvider, Boolean storeTimestampInUtc, Protocol connectionProtocol, Nullable`1 timeToLive)

Looking at the code for Microsoft.Azure.DocumentDB.Client.DocumentClient, a new parameter was added to the constructor and set to default as NULL but just updating the NuGet Package causes it to break.

**Comment by saleem-mirza** [comment]
@acgritt, thanks for reporting this issue. I'll investigate it over weekend.

**Comment by saleem-mirza** [comment]
@acgritt, Please try latest pre-release version (3.6.8-dev-00148) and let me know if it works or not.

```PowerShell
Install-Package Serilog.Sinks.AzureDocumentDb -Pre
```

**Comment by aagarwal10** [comment]
@saleem-mirza - any idea when you can push this fix as a released version ??
Thanks,

**Comment by aagarwal10** [comment]
@saleem-mirza - We are starting a new aspnet core project very soon and would love to use this sink for logging.

**Comment by saleem-mirza** [comment]
@aagarwal10 I'm traveling and hopping to be back in my desk by 20th. I'll release it soon.

**Comment by aagarwal10** [comment]
@saleem-mirza - Thanks, Appreciate it.
